"""Central threshold configuration for rule-based analytics."""

# Priority thresholds
PRIORITY_HIGH_THRESHOLD = 85.0
PRIORITY_MEDIUM_THRESHOLD = 65.0

# Sales thresholds
MAJOR_SALES_DECLINE_PERCENT = 30.0
LOW_TARGET_ACHIEVEMENT_PERCENT = 70.0

# Inventory thresholds
CRITICAL_STOCK_RATIO = 0.50
SEVERE_STOCK_RATIO = 0.25
INVENTORY_COMPLAINT_THRESHOLD = 20
INVENTORY_HIGH_SEVERITY_COMPLAINT_THRESHOLD = 5

# Complaint thresholds
COMPLAINT_OUTLIER_MULTIPLIER = 1.50

# Vendor thresholds
VENDOR_AVERAGE_DELAY_DAYS_THRESHOLD = 5.0
VENDOR_DELAYED_DELIVERIES_THRESHOLD = 3
VENDOR_LOW_QUALITY_RATING_THRESHOLD = 3.5

# Finance thresholds
LOW_OPERATING_PROFIT_MARGIN_PERCENT = 10.0