"""Central threshold configuration for rule-based analytics."""

# Priority thresholds
PRIORITY_HIGH_THRESHOLD = 85.0
PRIORITY_MEDIUM_THRESHOLD = 65.0

# Priority scoring configuration
PRIORITY_HIGH_SEVERITY_POINTS = 55.0
PRIORITY_MEDIUM_SEVERITY_POINTS = 35.0
PRIORITY_LOW_SEVERITY_POINTS = 15.0
PRIORITY_CROSS_AREA_BONUS = 7.0
PRIORITY_MAX_CROSS_AREA_BONUS = 14.0
PRIORITY_ADDITIONAL_HIGH_FINDING_BONUS = 10.0
PRIORITY_MAX_ADDITIONAL_HIGH_BONUS = 20.0
PRIORITY_FINDING_VOLUME_BONUS = 1.0
PRIORITY_MAX_FINDING_VOLUME_BONUS = 8.0

# Sales thresholds
STORE_SALES_DECLINE_PERCENT = 20.0
PRODUCT_SALES_DECLINE_PERCENT = 30.0
CATEGORY_SALES_DECLINE_PERCENT = 20.0
REGIONAL_SALES_DECLINE_PERCENT = 20.0
LOW_TARGET_ACHIEVEMENT_PERCENT = 70.0
PRODUCT_TO_CATEGORY_AVERAGE_RATIO = 0.60
MINIMUM_PRODUCT_PREVIOUS_MONTH_SALES = 50000.0

# Inventory thresholds
LOW_STOCK_RATIO = 0.80
STOCKOUT_RISK_RATIO = 0.50
SEVERE_STOCK_RATIO = 0.25
OVERSTOCK_RATIO = 3.0
SEVERE_OVERSTOCK_RATIO = 5.0
NEAR_EXPIRY_DAYS = 30
URGENT_EXPIRY_DAYS = 7
INVENTORY_COMPLAINT_THRESHOLD = 20
INVENTORY_HIGH_SEVERITY_COMPLAINT_THRESHOLD = 5

# Complaint thresholds
COMPLAINT_OUTLIER_MULTIPLIER = 1.50
REPEATED_COMPLAINT_CATEGORY_MULTIPLIER = 1.25
COMPLAINT_GROWTH_PERCENT = 20.0
UNRESOLVED_COMPLAINT_AGE_DAYS = 7
URGENT_UNRESOLVED_COMPLAINT_AGE_DAYS = 14

# Vendor thresholds
VENDOR_AVERAGE_DELAY_DAYS_THRESHOLD = 5.0
VENDOR_DELAYED_DELIVERIES_THRESHOLD = 3
VENDOR_LOW_QUALITY_RATING_THRESHOLD = 3.5
VENDOR_LOW_ON_TIME_DELIVERY_RATE = 70.0
VENDOR_PARTIAL_DELIVERY_THRESHOLD = 2

# Finance thresholds
LOW_OPERATING_PROFIT_MARGIN_PERCENT = 10.0